### ISSUE TITLE
No such file or directory: './preprocessed/train\\20230409020738.200.pkl'

### ISSUE THREAD

**Issue by GaoLL1026** [ztsrxh/RoadBEV#6]
When I execute the Python train.py -- lr 8e-4 command, the following error always occurs. I also tried to regenerate the GT labels, but this did not help me. I look forward to your answer.
Training RoadBEV mono!
Dataset size - train: 1210, test: 371
Num params: 26646334
Logging dir:/ Checkpoints/20240426020334
0% | | 0/50 [00:56<?,? It/s]
Traceback (most recent call last):
File "D: \ MasterStudents \ 2022 \ gaole \ RoadBEV main \ train. py", line 178, in<module>
Train()
File "D: \ MasterStudents \ 2022 \ gaole \ RoadBEV main \ train. py", line 26, in train
For i, sample in enumerate (train_loader):
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ utils \ data \ dataloader. py", line 630, in __ text__
Data=self_ Next_data()
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ utils \ data \ dataloader. py", line 1345, in next_data
Return self_ Process_data (data)
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ utils \ data \ dataloader. py", line 1371, in process_data
Data.rerase()
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ _utils. py", line 694, in rearase
Raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0
Original Traceback (most recent call last):
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ utils \ data \ _utils \ worker. py", line 308, in _worker_loop
Data=fetcher. fetch (index)
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ utils \ data \ _utils \ fetch. py", line 51, in fetch
Data=[self. dataset [idx] for idx in possibly_batched_index]
File "D: \ ana \ envs \ YOLO \ lib \ site packages \ torch \ utils \ data \ _utils \ fetch. py", line 51, in<listcomp>
Data=[self. dataset [idx] for idx in possibly_batched_index]
File "D: \ MasterStudents \ 2022 \ gaole \ RoadBEV main \ utilities \ dataset. py", line 212, in _getitem__
Ele_gt, ele_mask=self. get_gt_preprocessed (sample_cur ['time '])
File "D: \ MasterStudents \ 2022 \ gaole \ RoadBEV main \ utilities \ dataset. py", line 172, in get_gt_processed
With open (os. path. coin (self. reprocessed_path, time)+'. pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/ Preprocessed/train \ \ 20230409020738.200. pkl '

**Comment by ztsrxh** [comment]
Something wrong with your path settings. Check it carefully.
